---
- name: Install common packages using apt
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - nginx

- name: Ensure automate.sh has executable permissions
  ansible.builtin.file:
    path: /root/ansible/script/runner.sh
    mode: '0755'

- name: Run automate.sh script
  ansible.builtin.shell: /root/ansible/script/runner.sh
  args:
    chdir: /root/ansible/script

- name: Configure Nginx as a reverse proxy
  copy:
    content: |
      server {
          listen 80;

          location / {
              proxy_pass http://127.0.0.1:8080;
          }
      }
    dest: /etc/nginx/sites-available/reverse-proxy
    owner: root
    group: root
    mode: '0644'

- name: Enable the reverse proxy configuration
  file:
    src: /etc/nginx/sites-available/reverse-proxy
    dest: /etc/nginx/sites-enabled/reverse-proxy
    state: link

- name: Remove default Nginx site if it exists
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Test Nginx configuration
  command: nginx -t
  register: nginx_test
  failed_when: nginx_test.rc != 0

- name: Reload Nginx to apply configuration
  service:
    name: nginx
    state: reloaded