---
- name: Install common packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop: "{{ common_packages }}"

- name: Pull frontend Docker image
  community.docker.docker_image:
    name: 426857564226.dkr.ecr.us-east-1.amazonaws.com/testujwal001
    tag: frontend
    source: pull

- name: Run frontend container
  community.docker.docker_container:
    name: frontend_container
    image: 426857564226.dkr.ecr.us-east-1.amazonaws.com/testujwal001:frontend
    ports:
      - "8080:80"
    state: started

- name: Pull backend Docker image
  community.docker.docker_image:
    name: 426857564226.dkr.ecr.us-east-1.amazonaws.com/testujwal001
    tag: backend
    source: pull

- name: Run backend container
  community.docker.docker_container:
    name: backend_container
    image: 426857564226.dkr.ecr.us-east-1.amazonaws.com/testujwal001:backend
    ports:
      - "3000:3000"
    state: started