---
- name: Install common packages using yum
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - nginx

- name: Ensure automate.sh has executable permissions
      ansible.builtin.file:
        path: ~/ansible/script/runner.sh
        mode: '0755'

    - name: Run automate.sh script
      ansible.builtin.shell: ~/ansible/script/runner.sh
      args:
        chdir: ~/ansible/script/